; PlatformIO Project Configuration - Launcher Ground Station
;
; Build & upload:
;   pio run -e launcher -t upload
;
; Monitor serial:
;   pio device monitor -b 115200

[env:launcher]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit BMP085 Library@^1.2.4
    mprograms/QMC5883LCompass@^1.2.3
    mikalhart/TinyGPSPlus@^1.1.0
    madhephaestus/ESP32Servo@^3.0.5
    Wire
upload_speed = 921600
