"""Generate the human-readable views of the evidence record.

Whole files (claim passports, traceability, discrepancy register) and marked
fragments inside hand-written documents are rendered from the JSON records.
`python -m evidence docs --check` fails when any of them is stale, so prose
cannot silently disagree with the record. Output is deterministic: no dates of
generation, commit hashes, or machine paths.
"""

import csv
import io
import posixpath
import re

from .common import EvidenceError, read_bytes, safe_path
from . import vocabulary as V

HEADER = "<!-- Generated by `python -m evidence docs` from evidence/*.json. Edit the records, not this file. -->\n"
FRAGMENT = re.compile(r"(<!-- evidence:(?P<name>[a-z-]+) -->\n)(?P<body>.*?)(<!-- /evidence:(?P=name) -->)", re.S)
# Hand-written documents that carry generated fragments.
FRAGMENT_FILES = ["README.md", "index.md", "docs/PROJECT_STATUS.md", "docs/PAPER_ALIGNMENT.md",
                  "docs/BOM.md", "docs/EVIDENCE_OBSERVATORY.md", "docs/SAFETY.md"]
GATES_PATH = "evidence/safety_gates.json"
BOM_PATH = "materials/bom.csv"


def link(from_file, target):
    """Relative Markdown link from one repository file to another, safe for spaces."""
    relative = posixpath.relpath(target, posixpath.dirname(from_file) or ".")
    return f"<{relative}>" if " " in relative else relative


def cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ")


def value(item):
    if item is None:
        return "none"
    if isinstance(item, bool):
        return str(item).lower()
    if isinstance(item, float):
        return f"{item:.6g}"
    if isinstance(item, list):
        return " – ".join(value(v) for v in item)
    return str(item)


def bound(b, unit):
    if not b:
        return "none stated"
    parts = [f"≥ {b['min']}" if "min" in b else None, f"≤ {b['max']}" if "max" in b else None,
             f"= {str(b['equals']).lower()}" if "equals" in b else None]
    suffix = f" {unit}" if unit and unit != "boolean" else ""
    return " and ".join(p for p in parts if p) + suffix


def result(r):
    label = r["label"]
    if r.get("evidence_class"):
        label += f" ({V.EVIDENCE_CLASSES[r['evidence_class']]['label'].lower()})"
    return label


def observed(r):
    if r["result"] == "not_measured":
        return "NOT MEASURED"
    if r["result"] == "requires_human_review":
        return "judgement, not a value"
    if r["observed"] is None:
        return r["reason"] or "no value"
    text = value(r["observed"])
    for alt in r.get("alternates", []):
        text += f"; {alt['label']}: {value(alt['observed'])} ({V.REQUIREMENT_RESULTS[alt['result']]})"
    return text


def table(headers, rows):
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    lines += ["| " + " | ".join(cell(c) for c in row) + " |" for row in rows]
    return "\n".join(lines) + "\n"


def bullets(items, empty="None recorded."):
    return "".join(f"- {item}\n" for item in items) if items else f"- {empty}\n"


# --------------------------------------------------------------------------- whole files

def passport_md(claim, review):
    path = f"docs/claims/{claim['id']}.md"
    artifacts = {a["id"]: a for a in review["artifacts"]}
    requirements = {r["id"]: r for r in review["requirements"]}
    predictions = {p["id"]: p for p in review["predictions"]}
    discrepancies = {d["id"]: d for d in review["discrepancies"]}
    fresh = claim["freshness"]
    gate_index = V.GATE_INDEX[claim["gate"]]
    next_gate = V.GATES[gate_index + 1][1] if gate_index + 1 < len(V.GATES) else "none"
    if fresh["review"]:
        review_text = (f"{claim['freshness_label']} — {fresh['review']['kind']} recorded {fresh['review']['recorded']} "
                       f"by {fresh['review']['recorded_by']}")
    else:
        review_text = "NEVER REVIEWED"
    out = [HEADER, f"# {claim['id']} — {claim['title']}\n\n",
           table(["Field", "Value"], [
               ["Status", f"**{claim['status_label']}** — {claim['status_meaning']}"],
               ["Strongest accepted evidence", claim["support_label"]],
               ["Evidence classes cited", ", ".join(V.EVIDENCE_CLASSES[c]["label"] for c in claim["evidence_classes"])],
               ["Gate reached", f"{claim['gate_label']} (next: {next_gate})"],
               ["Last review", review_text],
           ]), "\n",
           f"**Question.** {claim['question']}\n\n**Current statement.** {claim['statement']}\n\n"]
    rows = [[r["id"], requirements[r["id"]]["text"], requirements[r["id"]]["check"].replace("_", " "),
             bound(requirements[r["id"]]["bound"], requirements[r["id"]]["unit"]),
             observed(requirements[r["id"]]), result(requirements[r["id"]])] for r in claim["requirement_results"]]
    out += ["## Requirements\n\n", table(["ID", "Requirement", "Check", "Bound", "Observed", "Result"], rows) if rows
            else "No requirement linked.\n", "\n"]
    if claim["predictions"]:
        out += ["## Predictions and measurements\n\n", prediction_table([predictions[p] for p in claim["predictions"]]), "\n"]
    out += ["## Known contradictions\n\n", bullets(claim["known_contradictions"], "None on record."), "\n",
            "## Open questions\n\n", bullets(claim["concerns"]), "\n",
            "## Discrepancies\n\n",
            bullets([f"[{d}](../DISCREPANCIES.md#{d.lower()}) ({V.DISCREPANCY_STATUSES[discrepancies[d]['status']]}) "
                     f"{discrepancies[d]['title']}" for d in claim["discrepancies_open"] + claim["discrepancies_resolved"]],
                    "None linked."), "\n",
            "## Assumptions\n\n", bullets(claim["assumptions"]), "\n",
            "## Limitations\n\n", bullets(claim["limitations"]), "\n",
            "## Measurement needed to close the next gate\n\n", bullets(claim["measurement_needed"]), "\n",
            "## Pre-registered experiments\n\n",
            bullets([f"{p} ({next(x for x in review['preregistrations'] if x['id'] == p)['status']})"
                     for p in claim["preregistrations"]], "None."), "\n",
            "## What this claim does not establish\n\n", bullets(claim["not_established"]), "\n",
            "## Evidence\n\n",
            table(["Artifact", "Class", "SHA-256 (first 12)", "What it is"],
                  [[f"[{artifacts[a]['path']}]({link(path, artifacts[a]['path'])})", artifacts[a]["class_label"],
                    f"`{artifacts[a]['sha256'][:12]}`", artifacts[a]["description"]] for a in claim["evidence"]]), "\n"]
    if claim["historical"]:
        out += ["## Earlier versions (failure archive)\n\n",
                bullets([f"[{artifacts[a]['path']}]({link(path, artifacts[a]['path'])}) — {artifacts[a]['description']}"
                         for a in claim["historical"]]), "\n"]
    out += ["## A change to any of these files makes the last review insufficient\n\n",
            bullets([f"`{p}`" for p in claim["affected_by_changes"]]), "\n",
            "---\n\n[All claims](README.md) · [Traceability](../TRACEABILITY.md) · "
            "[Discrepancies](../DISCREPANCIES.md) · [Evidence Observatory](../EVIDENCE_OBSERVATORY.md)\n"]
    return "".join(out)


def prediction_table(predictions):
    rows = []
    for p in predictions:
        if p["measurements"]:
            last = p["measurements"][-1]
            measured, abs_err = value(last["measured"]), value(last["absolute_error"])
            rel = value(last["relative_error"]) if last["relative_error"] is not None else "not computable"
        else:
            measured, abs_err, rel = "NOT MEASURED", "—", "—"
        criterion = f"{p['acceptance']['type']} ± {p['acceptance']['tolerance']}" if p["acceptance"] else "not pre-registered"
        drift = f" · PREDICTION DRIFT: {p['drift']}" if p["drift"] else ""
        rows.append([p["id"], f"{p['quantity']} ({p['condition']})",
                     f"{value(p['predicted'])} {p['unit']} [{V.EVIDENCE_CLASSES[p['evidence_class']]['label'].lower()}]",
                     value(p["model_uncertainty"]) if p["model_uncertainty"] is not None else "not quantified",
                     measured, abs_err, rel, criterion, p["result_label"] + drift])
    return table(["ID", "Quantity (condition)", "Predicted", "Model uncertainty", "Measured", "Abs. error",
                  "Rel. error", "Criterion", "Result"], rows)


def claims_index_md(review):
    rows = [[f"[{c['id']}]({c['id']}.md)", c["title"], c["status_label"], c["support_label"], c["gate_label"],
             ", ".join(r["id"] for r in c["requirement_results"] if r["result"] in ("not_satisfied", "conflicting")) or "none",
             ", ".join(c["discrepancies_open"]) or "none", c["freshness_label"]] for c in review["claims"]]
    ladder = table(["Class", "Physical", "What it can show"],
                   [[v["label"], "yes" if v["physical"] else "no", v["meaning"]] for v in V.EVIDENCE_CLASSES.values()])
    statuses = table(["Status", "Meaning"], [[label, meaning] for label, meaning in V.CLAIM_STATUSES.values()])
    return (HEADER + "# Claim passports\n\n" + counts_sentence(review) + "\n\n" +
            table(["Claim", "Title", "Status", "Strongest accepted evidence", "Gate reached",
                   "Failing or disputed requirements", "Open discrepancies", "Review"], rows) +
            "\nSupport is derived from the classes of cited evidence and cannot be authored. Physical classes count "
            "only when a named human has accepted the bench session behind them.\n\n## Claim statuses\n\n" + statuses +
            "\n## Evidence ladder\n\n" + ladder +
            "\n## Validation gates\n\n" + " → ".join(label for _, label in V.GATES) +
            "\n\nGates from INERT BENCH SETUP onward require a human-registered pre-registration or a human-accepted "
            "inert measurement. No AI model, CI run, or repository setting can move a claim across them.\n")


def traceability_md(review):
    artifacts = {a["id"]: a for a in review["artifacts"]}
    path = "docs/TRACEABILITY.md"
    rows = []
    for r in review["requirements"]:
        rows.append([r["id"], ", ".join(f"[{c}](claims/{c}.md)" for c in r["claims"]), r["text"],
                     "; ".join(r["assumptions"]) or "none stated",
                     "<br>".join(f"[{artifacts[a]['path']}]({link(path, artifacts[a]['path'])})" for a in r["implementation"]) or "none",
                     "<br>".join(f"[{artifacts[a]['path']}]({link(path, artifacts[a]['path'])})" for a in r["tests"]) or "none",
                     r["check"].replace("_", " "), bound(r["bound"], r["unit"]), observed(r), result(r)])
    by_check = {}
    for r in review["requirements"]:
        by_check.setdefault(r["check"], []).append(r["id"])
    categories = table(["How it is checked", "Meaning", "Requirements"],
                       [[key.replace("_", " "), meaning, ", ".join(by_check.get(key, [])) or "none"]
                        for key, meaning in V.CHECK_TYPES.items()])
    consistency = table(["Check", "Claims", "Description", "Left", "Right", "Result"],
                        [[k["id"], ", ".join(k["claims"]), k["description"], value(k["left"]), value(k["right"]), k["result"]]
                         for k in review["consistency"]])
    preregs = table(["ID", "Experiment", "Status", "Registered by", "Interpretation rule"],
                    [[p["id"], p["title"], p["status"], p["registered_by"] or "not registered by a human", p["interpretation_rule"]]
                     for p in review["preregistrations"]])
    return (HEADER + "# Requirement and prediction traceability\n\n"
            "Requirement → assumption → implementation → test → evaluated result → claim. A result carries the class of "
            "evidence it was computed from: SATISFIED (analytical) means a calculation met the bound, not that hardware did.\n\n"
            "## How each requirement can be closed\n\n" + categories +
            "\n## Requirement matrix\n\n" + table(["ID", "Claims", "Requirement", "Assumptions", "Implementation", "Tests",
                                                   "Check", "Bound", "Observed", "Result"], rows) +
            "\n## Prediction ledger and model-to-measurement comparison\n\n"
            "Predicted values are frozen when registered; a later model output that differs fails `python -m evidence check` "
            "as PREDICTION DRIFT. An empty measurement is NOT MEASURED, never zero.\n\n" + prediction_table(review["predictions"]) +
            "\n## Numerical consistency checks\n\n" + consistency +
            "\n## Pre-registered experiments\n\nWritten before testing so success criteria cannot be chosen after the result. "
            "`proposed` entries were drafted and await adoption by a named human.\n\n" + preregs)


def discrepancies_md(review):
    artifacts = {a["id"]: a for a in review["artifacts"]}
    path = "docs/DISCREPANCIES.md"
    counts = {}
    for d in review["discrepancies"]:
        counts[(d["status"], d["effect"])] = counts.get((d["status"], d["effect"]), 0) + 1
    summary = table(["Status", "Effect", "Count"],
                    [[V.DISCREPANCY_STATUSES[s], V.DISCREPANCY_EFFECTS[e], n] for (s, e), n in sorted(counts.items())])
    out = [HEADER, "# Discrepancy register\n\n"
           "Two parts of the project disagreeing is information. Each entry names both sides, the claims it affects, "
           "and the next action. Resolved entries stay, with what resolved them; a record correction is not an "
           "engineering review.\n\n", summary, "\n"]
    for d in review["discrepancies"]:
        sides = []
        for s in d["sides"]:
            target = artifacts[s["artifact"]]["path"] if "artifact" in s else s["path"]
            sides.append(f"[{target}]({link(path, target)}): {s['says']}")
        out += [f"## {d['id']}\n\n**{d['title']}**\n\n",
                table(["Field", "Value"], [
                    ["Status", V.DISCREPANCY_STATUSES[d["status"]]], ["Effect", V.DISCREPANCY_EFFECTS[d["effect"]]],
                    ["Kind", d["kind"].replace("_", " ") + " — " + V.DISCREPANCY_KINDS[d["kind"]]],
                    ["Claims", ", ".join(f"[{c}](claims/{c}.md)" for c in d["claims"]) or "none"]]),
                "\n", bullets(sides), "\n", f"**Next action.** {d['next_action']}\n\n"]
        if d.get("progress"):
            out.append(f"**Progress.** {d['progress']}\n\n")
        if d["resolution"]:
            out.append(f"**Resolution.** {d['resolution']} ({d['resolved_by']})\n\n")
        out.append(f"*Found by:* {d['found_by']}\n\n")
    out += ["## Failure archive\n\nSuperseded models, rejected tests, and historical claims, kept byte for byte. "
            "The digest in `evidence/archive/index.json` makes any edit detectable.\n\n",
            table(["File", "Kind", "Originally", "Why archived", "Discrepancies"],
                  [[f"[{a['path']}]({link(path, a['path'])})", a["kind"].replace("_", " "), a["original_path"],
                    a["reason"], ", ".join(a["discrepancies"]) or "—"] for a in review["archive"]])]
    return "".join(out)


# --------------------------------------------------------------------------- fragments

def counts_sentence(review):
    c = review["counts"]
    status = c["claim_status"]
    parts = [f"{c['claims']} claims",
             f"{status.get('contradicted', 0)} contradicted",
             f"{status.get('open', 0)} unresolved",
             f"{status.get('supported_within_limits', 0)} supported within stated limits",
             f"{c['accepted_physical_measurements']} accepted physical measurements",
             f"{c['discrepancies_open']} open discrepancies of {c['discrepancies_total']}",
             f"{c['predictions_not_measured']} of {c['predictions_total']} predictions not measured"]
    return "**Record state:** " + " · ".join(parts) + "."


def claims_fragment(review, from_file):
    rows = [[f"[{c['id']}]({link(from_file, 'docs/claims/' + c['id'] + '.md')})", c["title"], f"**{c['status_label']}**",
             c["support_label"],
             ", ".join(f"{r['id']} {r['label']}" for r in c["requirement_results"]
                       if r["result"] in ("not_satisfied", "conflicting")) or "none failing",
             ", ".join(c["discrepancies_open"]) or "none"] for c in review["claims"]]
    return counts_sentence(review) + "\n\n" + table(
        ["Claim", "Subject", "Status", "Strongest accepted evidence", "Failing or disputed requirements", "Open discrepancies"], rows)


def bom(root):
    rows = list(csv.DictReader(io.StringIO(read_bytes(safe_path(root, BOM_PATH)).decode("utf-8"))))
    total, estimated, purchased = 0.0, 0, 0
    lines = []
    for row in rows:
        qty = float(row["qty"])
        unit = float(row["unit_price_usd"]) if row["unit_price_usd"] else None
        line_total = qty * unit if unit is not None else None
        if line_total is None:
            raise EvidenceError(f"BOM line {row['item']!r} has no unit price; an unknown price cannot be summed")
        total += line_total
        estimated += row["price_basis"] == "estimate"
        purchased += bool(row["purchased_price_usd"])
        lines.append([row["item"], row["qty"], row["unit"], f"${unit:g}", row["price_basis"],
                      f"${float(row['purchased_price_usd']):g}" if row["purchased_price_usd"] else "not recorded",
                      row["source_date"] or "not recorded", row["reused"], row["notes"]])
    return rows, total, estimated, purchased, lines


def cost_fragment(root):
    rows, total, estimated, purchased, _ = bom(root)
    return (f"Estimated prototype subtotal: **${total:.0f}** from {len(rows)} BOM lines "
            f"({estimated} estimates, {purchased} purchased prices recorded, source dates not recorded, "
            f"shipping and spares excluded). An estimate is not a purchase record; see [BOM](docs/BOM.md) and D-021.\n")


def bom_fragment(root):
    rows, total, estimated, purchased, lines = bom(root)
    return (table(["Item", "Qty", "Unit", "Unit price", "Price basis", "Purchased price", "Source date", "Reused", "Notes"], lines) +
            f"\n**Subtotal of estimates:** ${total:.0f} across {len(rows)} lines. {estimated} lines are estimates; "
            f"{purchased} purchased prices are recorded. Shipping, spares, and tax are excluded. Source: `{BOM_PATH}`.\n")


def gates_fragment(root, from_file):
    from .common import load_json

    gates = load_json(read_bytes(safe_path(root, GATES_PATH)))["gates"]
    rows = []
    for gate in gates:
        sources = sorted({check["path"] for check in gate["source"]})
        rows.append([gate["id"], gate["gate"], gate["location"], gate["behavior"],
                     "<br>".join(f"[{p}]({link(from_file, p)})" for p in sources), "NOT MEASURED"])
    return (table(["ID", "Gate", "Where", "Behavior", "Source checked by tests", "Bench evidence"], rows) +
            f"\nGenerated from `{GATES_PATH}`. `tests/test_firmware_safety.py` fails if any gate's source text changes. "
            "Source inspection shows the gate is implemented; it does not show the hardware behaves that way.\n")


def fragments_for(path, review, root):
    return {
        "claims-table": lambda: claims_fragment(review, path),
        "counts": lambda: counts_sentence(review) + "\n",
        "cost": lambda: cost_fragment(root),
        "bom-table": lambda: bom_fragment(root),
        "safety-gates": lambda: gates_fragment(root, path),
    }


def render_all(root, review):
    """Map of repository path -> expected full content."""
    out = {"docs/claims/README.md": claims_index_md(review), "docs/TRACEABILITY.md": traceability_md(review),
           "docs/DISCREPANCIES.md": discrepancies_md(review)}
    for claim in review["claims"]:
        out[f"docs/claims/{claim['id']}.md"] = passport_md(claim, review)
    for path in FRAGMENT_FILES:
        target = safe_path(root, path)
        if not target.is_file():
            continue
        text = read_bytes(target).decode("utf-8")
        makers = fragments_for(path, review, root)

        def replace(match):
            name = match.group("name")
            if name not in makers:
                raise EvidenceError(f"{path}: unknown evidence fragment {name}")
            return match.group(1) + makers[name]() + match.group(4)

        out[path] = FRAGMENT.sub(replace, text)
    return out


def check(root, review):
    stale = []
    for path, content in sorted(render_all(root, review).items()):
        target = safe_path(root, path)
        if not target.is_file() or read_bytes(target).decode("utf-8") != content:
            stale.append(path)
    return stale


def write(root, review):
    written = []
    for path, content in sorted(render_all(root, review).items()):
        target = safe_path(root, path)
        if target.is_file() and read_bytes(target).decode("utf-8") == content:
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8", newline="\n")
        written.append(path)
    return written

