// Generated by tools/generate_protocol.py. Edit protocol/project33_protocol.json instead.
#pragma once

namespace Project33Protocol {
    static constexpr const char* READY = "READY";
    static constexpr const char* IGNITED = "IGNITED";
    static constexpr const char* CMD_ARM = "ARM";
    static constexpr const char* CMD_IGNITE = "IGNITE";
    static constexpr const char* CMD_CALIBRATE = "CALIBRATE";
    static constexpr const char* CMD_DUMPLOG = "DUMPLOG";
    static constexpr const char* DASHBOARD_LAUNCH = "launch";
    static constexpr const char* DASHBOARD_CALIBRATE = "calibrate";
    static constexpr const char* DASHBOARD_DUMPLOG = "dumplog";
    static constexpr const char* DATA_PREFIX = "DATA,";
    static constexpr const char* STATUS_PREFIX = "STATUS:";
    static constexpr const char* ENV_PREFIX = "ENV,";
    static constexpr const char* LOG_PREFIX = "LOG";
    static constexpr const char* LOG_START = "LOG_START";
    static constexpr const char* LOG_END = "LOG_END";
    static constexpr const char* CMD_ACK_LAUNCH_READY = "CMD_ACK:launch_ready";
    static constexpr const char* CMD_REJECT_LAUNCH_NOT_READY = "CMD_REJECT:launch_not_ready";
    static constexpr const char* CMD_REJECT_DASHBOARD_LAUNCH_DISABLED = "CMD_REJECT:dashboard_launch_disabled";
    static constexpr const char* CMD_REJECT_PID_INVALID = "CMD_REJECT:pid_invalid";
    static constexpr const char* CMD_REJECT_UNKNOWN_COMMAND = "CMD_REJECT:unknown_command";
    static constexpr const char* ABORT_PREFIX = "ABORT:";
}
