import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = ROOT / "protocol" / "project33_protocol.json"
HEADER_PATH = ROOT / "Firmware" / "shared" / "Project33Protocol.h"
MARKDOWN_PATH = ROOT / "docs" / "PROTOCOL.md"


def load_protocol(path=DEFAULT_SOURCE):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def render_header(protocol):
    lines = [
        "// Generated by tools/generate_protocol.py. Edit protocol/project33_protocol.json instead.",
        "#pragma once",
        "",
        "namespace Project33Protocol {",
    ]
    for name, value in protocol["firmware_constants"].items():
        lines.append(f'    static constexpr const char* {name} = "{value}";')
    lines.extend(["}", ""])
    return "\n".join(lines)


def render_markdown(protocol):
    lines = [
        "# Project 33 Protocol Reference",
        "",
        "Generated from `protocol/project33_protocol.json`.",
        "",
        "## Firmware Constants",
        "",
        "| Name | Value |",
        "|------|-------|",
    ]
    for name, value in protocol["firmware_constants"].items():
        lines.append(f"| `{name}` | `{value}` |")

    lines.extend(
        [
            "",
            "## Messages",
            "",
            "| Direction | Format | Purpose |",
            "|-----------|--------|---------|",
        ]
    )
    for message in protocol["messages"]:
        lines.append(
            "| {direction} | `{format}` | {purpose} |".format(
                direction=message["direction"],
                format=message["format"],
                purpose=message["purpose"],
            )
        )
    lines.append("")
    return "\n".join(lines)


def write_outputs(protocol, header_path=HEADER_PATH, markdown_path=MARKDOWN_PATH):
    header = Path(header_path)
    markdown = Path(markdown_path)
    header.parent.mkdir(parents=True, exist_ok=True)
    markdown.parent.mkdir(parents=True, exist_ok=True)
    header.write_text(render_header(protocol), encoding="utf-8")
    markdown.write_text(render_markdown(protocol), encoding="utf-8")


def check_outputs(protocol, header_path=HEADER_PATH, markdown_path=MARKDOWN_PATH):
    expected = {
        Path(header_path): render_header(protocol),
        Path(markdown_path): render_markdown(protocol),
    }
    mismatches = []
    for path, content in expected.items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            mismatches.append(path)
    return mismatches


def main():
    parser = argparse.ArgumentParser(description="Generate Project 33 protocol artifacts.")
    parser.add_argument("--check", action="store_true", help="Fail if generated artifacts are stale")
    args = parser.parse_args()

    protocol = load_protocol()
    if args.check:
        mismatches = check_outputs(protocol)
        if mismatches:
            for path in mismatches:
                print(f"stale: {path}")
            raise SystemExit(1)
    else:
        write_outputs(protocol)


if __name__ == "__main__":
    main()
